apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-metrics-generator
  namespace: keda-testing
  labels:
    app: prometheus-metrics-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-metrics-generator
  template:
    metadata:
      labels:
        app: prometheus-metrics-generator
    spec:
      containers:
      - name: prometheus-metrics-generator
        image: thabiger/prometheus-metrics-generator:latest
        ports:
        - containerPort: 8001
          name: web
        - containerPort: 9100
          name: metrics
        env:
        - name: PROMETHEUS_PORT
          value: "9100"
        - name: WEB_PORT
          value: "8001"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        volumeMounts:
        - name: config
          mountPath: /app/config
      volumes:
      - name: config
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics-generator
  namespace: keda-testing
  labels:
    app: prometheus-metrics-generator
spec:
  selector:
    app: prometheus-metrics-generator
  ports:
  - name: web
    port: 8001
    targetPort: 8001
  - name: metrics
    port: 9100
    targetPort: 9100
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-metrics-generator
  namespace: keda-testing
  labels:
    app: prometheus-metrics-generator
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: prometheus-metrics-generator
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
