name: Update Docker Hub Repository

on:
  push:
    branches:
      - main
    paths:
    - README.md
    - .github/workflows/update-docker-hub-info.yml

jobs:
  update-dockerhub-repo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Docker Hub Description
      uses: peter-evans/dockerhub-description@v4
      with:
        username: "${{ vars.DOCKERHUB_USERNAME }}"
        password: "${{ secrets.DOCKERHUB_TOKEN }}"
        repository: "${{ vars.DOCKERHUB_USERNAME }}/prometheus-metrics-generator"
        short-description: "A Python application that generates Prometheus metrics for testing purposes, supporting multiple waveform types and interactive previews."